name: "Check whether new release is available"
on:
    workflow_dispatch: 
    schedule:
        - cron: '0 */4 * * *'

jobs:
    checkout-transfer-market-api:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
              with:
                repository: "felipeall/transfermarkt-api"
                path: './transfermarket-api'
            - id: check
              name: 'Check if build is required or not'
              working-directory: "./transfermarket-api"
              run: |
                if [ "${{github.sha}}" = "$latest_sha" ]; then
                    echo "true=$isBuild" >> $GITHUB_OUTPUT    
                else
                    echo "true=$isBuild" >> $GITHUB_OUTPUT
                fi
            - name: Set up QEMU
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              uses: docker/setup-buildx-action@v3
            
            - name: 'Login to GitHub Container Registry'
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.DOCKER_TOKEN}}

            - name: Build Docker Image
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              working-directory: "./transfermarket-api"
              run: | 
                docker build . -t "ghcr.io/sureshchhatwani12/transfermarketapi:${{github.sha}}"
            - name: Push Docker Image
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              working-directory: "./transfermarket-api"
              run: | 
                docker push "ghcr.io/sureshchhatwani12/transfermarketapi:${{github.sha}}"
