name: "Check whether new release is available"
on:
    workflow_dispatch: 
    schedule:
        - cron: '0 */4 * * *'

jobs:
    checkout-transfer-market-api:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
              with:
                repository: "felipeall/transfermarkt-api"
                path: './transfermarket-api'
            - name: 'Check if build is required or not'
              run: |
                latest_sha=$(git rev-parse HEAD)
                # Compare the provided SHA with the latest SHA and confirm whether build is required
                if [ "${{ vars.LATEST_SHA }}" = "$latest_sha" ]; then
                    echo "Build is not required"
                else
                    echo "Build is required"
                fi

