name: "Check whether new release is available"
on:
    workflow_dispatch: 
    schedule:
        - cron: '0 */4 * * *'

jobs:
    checkout-transfer-market-api:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
              with:
                repository: "felipeall/transfermarkt-api"
                path: './transfermarket-api'
            - id: check
              name: 'Check if build is required or not'
              working-directory: "./transfermarket-api"
              run: |
                latest_sha=$(git rev-parse HEAD)
                # Compare the provided SHA with the latest SHA and confirm whether build is required
                if [ "${{vars.LATEST_SHA}}" = "$latest_sha" ]; then
                    echo "true=$isBuild" >> $GITHUB_OUTPUT    
                else
                    echo "true=$isBuild" >> $GITHUB_OUTPUT
                fi
            - name: Extract Docker metadata
              id: meta
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              uses: docker/metadata-action@v3
              with:
                  images: ghcr.io/sureshchhatani12/transfermktapidemo
                  tags: |
                    type=ref,event=branch,suffix=-{{ sha }}
                    type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
                  flavor: |
                    latest=false
            - name: Set up QEMU
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              uses: docker/setup-buildx-action@v3
            
            - name: 'Login to GitHub Container Registry'
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{github.actor}}
                password: ${{secrets.DOCKER_TOKEN}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              if: ${{ steps.check.outputs.isBuild }} == 'true'
              with:
                  # the Dockerfile is at the root of the workspace
                  context: ./transfermarket-api
                  # only push when requested
                  push: true
                  # pass the output of the metadata action
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  # use layer caching
                  # The mode=max is to also cache the builder image
                  # (vs only the final image - mode: min)
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

