# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - opentransfermktapi1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    outputs:
      imageTag: ${{steps.getsha.outputs.latest_sha}}"
    steps:
    - uses: actions/checkout@v4
      with:
        repository: "felipeall/transfermarkt-api"
        path: './transfermarket-api'
    
    - id: getsha
      working-directory: "./transfermarket-api"
      name: 'Get SHA'
      run: | 
        latest_sha=$(git rev-parse HEAD)
        echo "Output [$latest_sha]"
        echo "latest_sha=$latest_sha" >> $GITHUB_OUTPUT  

    - id: check
      name: 'Check if build is required or not'
      working-directory: "./transfermarket-api"
      run: |
        latest_sha=$(git rev-parse HEAD)
        # Compare the provided SHA with the latest SHA and confirm whether build is required
        if [ "${{vars.LATEST_SHA}}" = "$latest_sha" ]; then
            echo "true=$isBuild" >> $GITHUB_OUTPUT    
        else
            echo "true=$isBuild" >> $GITHUB_OUTPUT
        fi

    - name: Set up Docker Buildx
      if: ${{ steps.check.outputs.isBuild }} == 'true'
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      if: ${{ steps.check.outputs.isBuild }} == 'true'
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{github.actor}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      if: ${{ steps.check.outputs.isBuild }} == 'true'
      with:
        push: true
        tags: ghcr.io/sureshchhatwani12/transfermarketapi:${{steps.getsha.outputs.latest_sha}}
        file: ../transfermarket-api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'opentransfermktapi1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_705a1ae5eb9b41878aeafbc4cdd93c08 }}
        images: 'ghcr.io/sureshchhatwani12/transfermarketapi:${{needs.build.outputs.imageTag}}'